### ISSUE TITLE
OpenShift: parity image reference (v1.9.6) broken 

### ISSUE THREAD

**Issue by karstengresch** [itp-world/blockchain-otc-dapp#11]
For documentation mainly (not pressure ;):

When deploying the app on OpenShift as described in https://github.com/itp-world/blockchain-otc-dapp/blob/master/openshift/README.md, the application cannot be started as the parity image isn't available anymore on DockerHub.

If you try to deploy the image, you get the error message:

> An error occurred while starting the deployment.
> Reason: cannot trigger a deployment for "parity" because it contains unresolved images

Expected behavior: Parity image gets pulled and pod started.

**Comment by drmartinberger** [comment]
Hi @karstengresch,

Parity image should be available: https://hub.docker.com/layers/parity/parity/stable/images/sha256-b2b0b50d51505f8ce9a108085dcc47b2c5f8100934e4efe714bf09b33d6c2f51

Not sure what went wrong for you.

BR, Martin

**Comment by karstengresch** [comment]
Hi @drmartinberger.

thanks for your reply! 

The [pull request](https://github.com/itp-world/blockchain-otc-dapp/pulls?q=is%3Apr+is%3Aclosed) itself explains what I mean ;)

So, here for documentation purposes:

[deploy.sh](https://github.com/itp-world/blockchain-otc-dapp/blob/master/openshift/deploy.sh) used a hard coded version 1.9.6 as well did [parity-template.yml](https://github.com/itp-world/blockchain-otc-dapp/blob/master/openshift/parity-template.yml) with the PARITY_VERSION value of "2.0.1"

Both 1.9.6 and 2.0.1 aren't available from Docker hub anymore AFAICS.

I changed it to "stable" which currently seems to point to 2.5.7 (see [parity release page](https://github.com/paritytech/parity-ethereum/releases/tag/v2.5.7)) though the image digest isn't the same which might be related to parity internals (see image below).

<img width="363" alt="image" src="https://user-images.githubusercontent.com/7924413/64515027-181a4380-d2ec-11e9-8b26-cd5d92d50234.png">

This ensures an available image gets pulled from DockerHub and still leaves the possibility to overwrite for running an older version (if available).

Best wishes,

Karsten

**Comment by karstengresch** [comment]
Tested by @drmartinberger and on my part, can be closed.
